# Generated by Django 3.2.6 on 2021-10-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_program_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(max_length=20)),
            ],
        ),
    ]
